# apiVersion: v1
# kind: Service
# metadata:
#   name: goserver-service
# spec:
#   selector:
#     app: goserver
#   type: ClusterIP
#   ports:
#   - name: goserver-service
#     port: 8080
#     protocol: TCP

# apiVersion: v1
# kind: Service
# metadata:
#   name: goserver-service
# spec:
#   selector:
#     app: goserver
#   type: NodePort
#   ports:
#   - name: goserver-service
#     port: 8080
#     protocol: TCP
#     nodePort: 30001 #30000-32767

apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: LoadBalancer
  ports:
  - name: goserver-service
    port: 8080
    protocol: TCP 